/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.EventoController;
import Controller.HospedagemController;
import com.formdev.flatlaf.IntelliJTheme;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;
import model.Evento;
import model.Hospedagem;
import model.Util;

/**
 * Classe responsável por controlar a adição de eventos em uma hospedagem
 *
 * @author 2020101202010138
 */
public class AddEvento extends javax.swing.JFrame {

    EventoController eventoController = new EventoController();
    HospedagemController hospedagemController = new HospedagemController();
    Hospedagem hosp;
    HospedagemDetalhes hd;
    Hospedagens hs;
    Evento e;

    /**
     * Construtor vazio.
     */
    public AddEvento() {
    }

    /**
     * Construtor que recebe uma hospedagem, detalhes de hospedagem e a tela com
     * uma lista de hospedagens.
     *
     * @param h : a hospedagem
     * @param hds : os detalhes de hospedagem
     * @param hd : as hospedagens
     */
    public AddEvento(Hospedagem h, HospedagemDetalhes hds, Hospedagens hd) {
        initComponents();
        this.hosp = h;
        this.hd = hds;
        this.hs = hd;
        listaEventDisp();
        inputCpf.setText(hosp.getCliente().getCpf());
        this.setTitle("Adicionar evento");
        this.setLocationRelativeTo(null);
    }

    public Hospedagem getHosp() {
        return hosp;
    }

    public Evento getEvent() {
        return e;
    }

    /**
     * Busca um evento pelo nome.
     *
     * @param n : o nome do evento a ser buscado
     * @return o objeto Evento correspondente ao nome especificado
     */
    public Evento buscarEvento(String n) {
        String nome = n;
        EventoController ec = new EventoController();
        Evento e = ec.buscarPorNome(nome);
        return e;
    }

    /**
     * Preenche a lista de eventos disponíveis em um componente de seleção.
     * Remove todos os itens existentes na lista antes de adicionar os eventos
     * disponíveis.
     */
    public void listaEventDisp() {
        EventoController ed = new EventoController();
        List<Evento> lista = ed.listarEvento();
        boxEventos.removeAllItems();
        for (Evento e : lista) {
            boxEventos.addItem(e.getNomeEvento());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputData = new javax.swing.JFormattedTextField();
        inputQtd = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        inputCpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        boxEventos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Adicionar evento");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel2.setText("Eventos");

        jLabel3.setText("Data ");

        try {
            inputData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputData.setText("01012000");

        inputQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel4.setText("Nº de participantes");

        try {
            inputCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCpf.setText("");

        jLabel7.setText("CPF do Cliente");

        btnCadastrar.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnCadastrar.setText("ADICIONAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        boxEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxEventos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxEventosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(boxEventos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(inputQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //botão para adicionar evento na hospedagem

        Util util = new Util();
        if (util.VerificaInput(this)) {
            e = buscarEvento(boxEventos.getSelectedItem().toString());
            eventoController.addEventoHosp(this);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        }
        hd.atualizaTbEventos();
        hs.atualizaTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void boxEventosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxEventosItemStateChanged
        //mudou evento box
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            inputData.setText(String.valueOf(eventoController.buscarPorNome(boxEventos.getSelectedItem().toString()).getData()));
        }
    }//GEN-LAST:event_boxEventosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        IntelliJTheme.setup(Setup.class.getResourceAsStream("/Gradianto_deep_ocean.theme.json"));

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxEventos;
    private javax.swing.JButton btnCadastrar;
    public javax.swing.JFormattedTextField inputCpf;
    public javax.swing.JFormattedTextField inputData;
    public javax.swing.JFormattedTextField inputQtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
