/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Controller.HospedagemController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Hospedagem;

/**
 * A classe Hospedagens é responsável por exibir e gerenciar as informações
 * relacionadas às hospedagens, incluindo a exibição de uma tabela com os dados
 * das hospedagens cadastradas.
 *
 * @author kaior
 */
public class Hospedagens extends javax.swing.JPanel {

    HospedagemController hospedagemController = new HospedagemController();

    /**
     * Construtor da classe Hospedagens.
     */
    public Hospedagens() {
        initComponents();
        tableHospedagens.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * Atualiza a tabela de hospedagens com os dados atualizados.
     */
    public void atualizaTabela() {
        List<Hospedagem> lista = hospedagemController.listarHospedagem();
        DefaultTableModel hospedagemTb = (DefaultTableModel) tableHospedagens.getModel();
        hospedagemTb.setNumRows(0);
        for (Hospedagem h : lista) {
            hospedagemTb.addRow(new Object[]{
                h.getId(),
                h.getCliente().getCpf(),
                h.getCliente().getNome(),
                h.getQuarto().getId(),
                h.getCheckin(),
                h.getCheckout(),
                h.getTotal()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHospedagens = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1281, 749));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 48)); // NOI18N
        jLabel1.setText("Hospedagens");

        tableHospedagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Quarto", "Data Check-In", "Data Check-Out", "Fatura atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHospedagens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableHospedagensMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableHospedagens);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(70, 870, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableHospedagensMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHospedagensMouseReleased
        //clicou nem uma linha da tabela
        HospedagemDetalhes hospedagemDetalhes = new HospedagemDetalhes(this);
        hospedagemDetalhes.setVisible(true);
        Hospedagem h;
        h = hospedagemController.buscaHospedagemId(Integer.parseInt(tableHospedagens.getValueAt(tableHospedagens.getSelectedRow(), 0).toString()));
        hospedagemDetalhes.lerHospedagem(h);
    }//GEN-LAST:event_tableHospedagensMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableHospedagens;
    // End of variables declaration//GEN-END:variables
}
